server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.240.248.218:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  rabbitmq:
    host: 47.240.248.218
  cloud:
    config:
      discovery:
        #开启Config服务发现支持
        enabled: true
        #指定server端的name,也就是server端spring.application.name的值
        service-id: tensquare-conifg
    bus:
      id: ${spring.application.name}:${spring.cloud.config.profile}:${random.value}
eureka:
  client:
    service-url:
      defaultZone: http://47.240.248.218:6868/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true
myvalue: a123
