server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://centos7.jacktong726.com:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  rabbitmq:
    host: alicloud.jacktong726.com
eureka:
  client:
    service-url:
      defaultZone: http://alicloud.jacktong726.com:6868/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true
myvalue: abc123123DSFSDFSDFSDF
